{
 "title": "VoltDB  General",
 "tags": [ "VoltDB" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (hostname) (voltdb_cpu_usage_percent) >= 0",
     "legendFormat": "VoltDB Process %"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100) >= 0 ",
     "legendFormat": "{{instance}} CPU OS"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{mode=\"idle\"}[1m])) * 100)  >= 0",
     "legendFormat": "{{instance}} CPU OS"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container) * 100",
     "legendFormat": "% CPU POD "
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\", cluster=\"$cluster\"}) by (container)",
     "legendFormat": "POD CPU"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"})\n",
     "legendFormat": "REQUEST"
    }
   ]
  },
  {
   "title": "initiators vs TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "voltdb_initiator_invocations", "legendFormat": "{{procname}}" },
    { "expr": "sum(voltdb_latency_tps)", "legendFormat": "TPS" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(voltdb_queue_max_wait_seconds) * 100",
     "legendFormat": "Max Queue Wait Time (s)"
    },
    {
     "expr": "voltdb_latency_four_nines_seconds * 100",
     "legendFormat": "99.99 Latency (s)"
    },
    {
     "expr": "max(irate (voltdb_procedure_max_execution_time_seconds {procedure=\"chargingdemoprocs.ReportQuotaUsage\"}[1m])) * 100",
     "legendFormat": "max rate ReportQuotaUsage latency"
    },
    {
     "expr": "max(voltdb_procedure_avg_execution_time_seconds{procedure=\"chargingdemoprocs.ReportQuotaUsage\"}) * 100",
     "legendFormat": "avg latency reportquotausage"
    }
   ]
  },
  {
   "title": "TPS, Transaction Failures and Aborts per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(voltdb_latency_tps)", "legendFormat": "TPS" },
    {
     "expr": "sum by (procedure) (voltdb_procedure_aborts)",
     "legendFormat": "{{procedure}}"
    },
    {
     "expr": "increase (voltdb_procedure_aborts[30s]) ",
     "legendFormat": "RATE {{procedure}}"
    }
   ]
  },
  { "title": "Now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "KFactor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdbbl_systeminformation{property=\"kfactor\"})",
     "legendFormat": "Sites Per Host"
    }
   ]
  },
  {
   "title": "Sites Per Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdbbl_systeminformation{property=\"sitesperhost\",instance=~\"vdb.*\"})",
     "legendFormat": "Sites Per Host"
    }
   ]
  },
  {
   "title": "Normal Cluster Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdbbl_systeminformation{property=\"fullclustersize\",instance=~\"vdb.*\"})"
    }
   ]
  },
  {
   "title": "Current Cluster Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdbbl_systeminformation{property=\"current_cluster_size\",instance=~\"vdb.*\"})"
    }
   ]
  },
  {
   "title": "VoltDB CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max (voltdb_cpu_usage_percent) >= 0",
     "legendFormat": "Max VoltDB CPU"
    }
   ]
  },
  {
   "title": "99th Percentile Latency (ms)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(voltdb_latency_99th_seconds)*1000"
    }
   ]
  },
  {
   "title": "VoltDB RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  (max (voltdb_memory_rss_bytes) / max(node_memory_MemTotal_bytes))*100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  { "title": "Transactions and Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Cluster  Latency (MS)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(voltdb_latency_99th_seconds)",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "avg(voltdb_latency_four_nines_seconds)",
     "legendFormat": "99.99th Percentile"
    },
    {
     "expr": "avg(voltdb_latency_three_nines_seconds) ",
     "legendFormat": "99.9th Percentile"
    },
    {
     "expr": "avg(voltdb_latency_five_nines_seconds) ",
     "legendFormat": "99.999th Percentile"
    },
    {
     "expr": "avg(voltdb_latency_99th_seconds) ",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "avg(voltdb_latency_median_seconds) ",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Transaction Counts per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (procedure)  (irate(voltdbbl_procedureprofile{measuretype=\"invocations\"}[1m]) > 0)",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "Workload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (procedure)  (voltdbbl_procedureprofile{measuretype=\"workloadpct\"})",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "SQL Statement Execution Time (> 1ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg by (procname)  (voltdbbl_organizedsqlstmtstats_avgtimens)>1000000",
     "legendFormat": "{{procname}}"
    }
   ]
  },
  {
   "title": "Transaction Latency (Inside VoltDB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (procedure) (voltdb_procedure_avg_execution_time_seconds) ",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "Client Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(voltdb_liveclients_outstanding_txns)",
     "legendFormat": "Unfinished Transactions VoltDB knows about"
    },
    {
     "expr": "sum(voltdb_liveclients_outstanding_reponse_messages)",
     "legendFormat": "Finished Transactions VoltDB is about to send back to the client"
    }
   ]
  },
  { "title": "RAM, Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "IO Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total[2m])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Disk: IO ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now",
     "legendFormat": "{{instance}} {{device}} IO Queue"
    }
   ]
  },
  {
   "title": "Disk:  Read & Write Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total[1m])/rate(node_disk_reads_completed_total[1m]) *100 > 0",
     "legendFormat": "{{instance}} {{ device}} Reads"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total[1m])/rate(node_disk_writes_completed_total[1m]) *100 > 0",
     "legendFormat": "{{instance}} {{ device}} Writes"
    }
   ]
  },
  {
   "title": "Filesystem space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail{mountpoint=\"/voltdbdata\"}",
     "legendFormat": "{{instance}} free space /voltdbdata"
    },
    {
     "expr": "node_filesystem_avail_bytes {mountpoint=\"/\"}",
     "legendFormat": "{{instance}} free space /"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/voltdbdatassd1\"}",
     "legendFormat": "{{instance}} free space {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/voltdbdatassd2\"}",
     "legendFormat": "{{instance}} free space {{mountpoint}}"
    }
   ]
  },
  {
   "title": "VoltDB RAM usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "    avg by (hostname) (voltdb_memory_rss_bytes/1024) ",
     "legendFormat": "{{hostname}} RAM use"
    },
    {
     "expr": "max(node_memory_MemTotal_bytes/1024)",
     "legendFormat": "Max  RAM"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(voltdb_liveclients_outstanding_txns)  ",
     "legendFormat": "Outstanding Client Transactions"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(voltdb_commandlog_outstanding_txns)",
     "legendFormat": "Command Log Outstanding Transactions"
    },
    {
     "expr": "avg(voltdb_commandlog_fsync_interval_seconds)",
     "legendFormat": "fsync interval (seconds)"
    },
    {
     "expr": "max(voltdb_procedure_max_execution_time_seconds{procedure=\"org.voltdb.sysprocs.SnapshotSave\"})",
     "legendFormat": "Snapshot Save Duration (Seconds)"
    },
    { "expr": "node_d" }
   ]
  },
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Topic data on disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)  (voltdb_topic_on_disk_bytes)  ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic data growth on disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (irate(voltdb_topic_on_disk_bytes[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Fetch Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "   sum by (topic) (irate(voltdb_topic_fetch_bytes[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Fetch Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "   sum by (topic) (irate(voltdb_topic_fetch_bytes[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Export", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 } },
  {
   "title": "Kafka CDR Generation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (topic)  (irate(voltdb_topic_last_offset[1m])) ",
     "legendFormat": "{{topic}} Kafka Offset"
    }
   ]
  },
  {
   "title": "Export Latency (Seconds) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (target) (voltdb_export_avg_latency_seconds{target!=\"\"})",
     "legendFormat": "{{target}} latency"
    }
   ]
  },
  {
   "title": "Export Lag (Seconds) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " min by (target) (time() - (voltdb_export_last_acked_timestamp{target!=\"\"}) / 1000000) < 10000000",
     "legendFormat": "{{target}} lag"
    }
   ]
  },
  {
   "title": "Export Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (target) (irate(voltdb_export_total_queued_tuples_count{target!=\"\"}[1m])) ",
     "legendFormat": "{{target}} per min"
    }
   ]
  },
  { "title": "Tables and Indexes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "Tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg  by (table) (voltdbbl_organizedtablestats{type!=\"export\"})",
     "legendFormat": "{{table}} rows"
    }
   ]
  },
  {
   "title": "Indices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg  by (index) (voltdbbl_organizedindexstats{type!=\"export\"})",
     "legendFormat": "{{index}} entries"
    }
   ]
  },
  { "title": "TTL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 175 } },
  {
   "title": "TTL - Rows deleted per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (tablename)    (irate(voltdb_ttl_deleted_rows[1m])) ",
     "legendFormat": "{{tablename}}"
    }
   ]
  },
  {
   "title": "TTL - Rows waiting for deletion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "voltdb_ttl_remaining_rows", "legendFormat": "{{tablename}}" }
   ]
  },
  {
   "title": "TTL - Deletion batch size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "voltdb_ttl_last_round_deleted_rows",
     "legendFormat": "{{tablename}}"
    }
   ]
  },
  {
   "title": "TTL Deletion CPU cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (procedure)  (voltdbbl_procedureprofile{measuretype=\"workloadpct\",procedure=\"org.voltdb.sysprocs.NibbleDeleteSP\"})"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 192 } },
  {
   "title": "Database level Task execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "voltdb_task_procedure_avg_execution_seconds{scope=\"DATABASE\"}",
     "legendFormat": "{{taskname}}"
    }
   ]
  },
  {
   "title": "Partition level Task execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (taskname)  ( voltdb_task_procedure_avg_execution_seconds{scope=\"PARTITIONS\"})",
     "legendFormat": "{{taskname}}"
    }
   ]
  },
  {
   "title": "Host level Task execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (hostname,taskname)  ( voltdb_task_procedure_avg_execution_seconds{scope=\"HOSTS\"})",
     "legendFormat": "{{hostname}} {{taskname}}"
    }
   ]
  },
  {
   "title": "Task Procedure Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (taskname)  ( voltdb_task_procedure_failures)",
     "legendFormat": " {{taskname}}"
    }
   ]
  },
  { "title": "Rebalance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 209 } },
  {
   "title": "Estimated Time Remaining",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "voltdb_rebalance_remaining_time_seconds>0",
     "legendFormat": "Remaining Time"
    }
   ]
  },
  {
   "title": "Rebalance Completion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "voltdb_rebalance_moved_ratio>0" }
   ]
  },
  {
   "title": "Rebalance MB per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "voltdb_rebalance_bytes_per_seconds*(1024*1024)>0",
     "legendFormat": "Rebalance MB/Sec"
    }
   ]
  },
  {
   "title": "Rebalance Rows per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "voltdb_rebalance_rows_per_seconds>0",
     "legendFormat": "Rebalance Rows/Sec"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 226 } },
  {
   "title": "GC Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 227 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(voltdb_gc_newgen_gc_count[1m])>0",
     "legendFormat": "{{hostname}} Newgen GC"
    },
    {
     "expr": "irate(voltdb_gc_oldgen_gc_count[1m])>0",
     "legendFormat": "{{hostname}} Oldgen GC"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 227 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "voltdb_gc_newgen_avg_gc_time_seconds>0",
     "legendFormat": "{{hostname}} GC Newgen time"
    },
    {
     "expr": "voltdb_gc_oldgen_avg_gc_time_seconds>0",
     "legendFormat": "{{hostname}} GC Oldgen time"
    }
   ]
  }
 ]
}